on: pull_request

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    name: reviewdog test
    steps:
    - uses: actions/checkout@v2
    - uses: shoooooman/go-complexity-analysis-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
